name: Claude Code

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  # 手動実行できるように残しておくと便利
  workflow_dispatch:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  claude:
    # コメント本文に @claude が含まれる場合のみ起動
    if: >
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code
        uses: anthropics/claude-code-action@main
        with:
          trigger_phrase: "@claude"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "30"
          # 任意の調整項目（必要ならアンコメントして使用）
          # model: "claude-3-7-sonnet"   # あなたのアカウントで利用可能なモデル名に固定
          # use_sticky_comment: "true"   # コメントを1つに集約
          # branch_prefix: "claude/"     # 生成ブランチの接頭辞
          # label_trigger: "claude"      # ラベルでも起動したい場合
